inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "build/**/*"
    - ".cache/**/*"
    - "patch/**/*"
    - "storage/**/*"
    - "playground/**/*" # User-facing ptrk usage experiments, not gem code
    - "lib/reality_marble/**/*" # Separate gem, has its own RuboCop config
    - "lib/picotorokko/templates/**/*" # User-facing templates, not core gem code
    - "test/commands/device_test.rb" # Excluded from test suite - see TODO.md [TODO-INFRASTRUCTURE-DEVICE-TEST]

plugins:
  - rubocop-performance
  - rubocop-rake

# String style configuration
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Allow Japanese comments in code
Style/AsciiComments:
  Enabled: false

# Disable frozen string literal comment requirement (Ruby 3.4+ default)
Style/FrozenStringLiteralComment:
  Enabled: false

# Metrics configuration - pragmatic thresholds for this project
Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 300
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Max: 30

Metrics/ParameterLists:
  Max: 5

# Test files have deeper nesting due to Dir.mktmpdir block + begin/ensure structure
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "picotorokko.gemspec" # Gem specification file with standard DSL structure

# Command processors in test mocking return boolean for success/failure, not predicates
Naming/PredicateMethod:
  Exclude:
    - "test/test_helper.rb" # process_*_command methods are command processors, not predicates
