inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "build/**/*"
    - ".cache/**/*"
    - "patch/**/*"
    - "storage/**/*"
    - "lib/pra/templates/**/*" # User-facing templates, not core gem code

plugins:
  - rubocop-performance
  - rubocop-rake

# String style configuration
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Allow Japanese comments in code
Style/AsciiComments:
  Enabled: false

# Disable frozen string literal comment requirement (Ruby 3.4+ default)
Style/FrozenStringLiteralComment:
  Enabled: false

# Metrics configuration - pragmatic thresholds for this project
Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Max: 30

Metrics/ParameterLists:
  Max: 5
