# M5Unified Ruby bindings for PicoRuby
# Auto-generated by PicoTorokko

# Classes:
# - M5Timer
# - timer_info_t

# This file serves as documentation for the C bindings
# implemented in src/m5unified.c
