# Picotest test suite for PicoRuby application
# Generated by: ptrk init
# Run with: ptrk device build --test && ptrk device flash && ptrk device monitor --test

# Test cases for application entry point
class AppTest < Picotest::Test
  def setup
    # Runs before each test (optional)
    # Use this to create fresh objects for each test
  end

  def test_example_assertion
    # Basic assertion example
    result = 1 + 1
    assert_equal 2, result, "1 + 1 should equal 2"
  end

  def test_stub_example_adc
    # Example: Stub ADC (Analog-to-Digital Converter) hardware
    # This allows testing without actual hardware connected

    # Uncomment to use:
    # adc = ADC.new(27)
    # stub(adc).read_raw { 750 }
    #
    # # Now adc.read_raw returns 750 instead of reading from hardware
    # assert_equal 750, adc.read_raw
  end

  def test_stub_any_instance_example_gpio
    # Example: Stub all instances of GPIO class
    # Useful when you don't control object creation

    # Uncomment to use:
    # stub_any_instance_of(GPIO).read { 1 }
    #
    # gpio1 = GPIO.new(5, GPIO::IN)
    # gpio2 = GPIO.new(10, GPIO::IN)
    #
    # # Both instances return stubbed value
    # assert_equal 1, gpio1.read
    # assert_equal 1, gpio2.read
  end

  def test_mock_example_with_call_count
    # Example: Mock with call count verification
    # Use when you need to verify a method was called N times

    # Uncomment to use:
    # mock_any_instance_of(I2C).write(2) { true }
    #
    # i2c = I2C.new(0, sda: 21, scl: 22)
    # i2c.write(0x50, [0x01])  # 1st call
    # i2c.write(0x51, [0x02])  # 2nd call
    #
    # # Teardown will verify write was called exactly 2 times
  end

  def test_conditional_stub_example
    # Example: Stub with conditional logic
    # Return different values based on arguments

    # Uncomment to use:
    # stub_any_instance_of(I2C).read do |address, length|
    #   case address
    #   when 0x50 then [0x12, 0x34]
    #   when 0x51 then [0xAA, 0xBB]
    #   else [0x00]
    #   end
    # end
    #
    # i2c = I2C.new(0, sda: 21, scl: 22)
    # assert_equal [0x12, 0x34], i2c.read(0x50, 2)
    # assert_equal [0xAA, 0xBB], i2c.read(0x51, 2)
  end

  def teardown
    # Runs after each test (optional)
    # Picotest doubles are automatically cleaned up
  end
end

# === Picotest Doubles Quick Reference ===
#
# Stub (replace return value, no call count verification):
#   stub(object).method_name { return_value }
#   stub_any_instance_of(ClassName).method_name { return_value }
#
# Mock (replace return value + verify call count):
#   mock(object).method_name(expected_calls) { return_value }
#   mock_any_instance_of(ClassName).method_name(expected_calls) { return_value }
#
# Assertions:
#   assert(condition)
#   assert_equal(expected, actual)
#   assert_nil(object)
#   assert_raise(ExceptionClass) { code }
#   assert_in_delta(expected, actual, delta)
#
# Learn more:
#   - SPEC.md: Device Testing section
#   - docs/DEVICE_TESTING_GUIDE.md
#   - https://github.com/picoruby/picoruby/tree/master/mrbgems/picoruby-picotest
