/*
 * M5Unified C Bindings for PicoRuby
 * Auto-generated by PicoTorokko
 */

#include <mrubyc.h>

/* Enum declarations */
/* Forward declarations */
static mrbc_class *c_M5Timer;
static mrbc_class *c_timer_info_t;

/* Extern declarations for wrapper functions */
extern constructor m5unified_m5timer_M5Timer(void void);
extern void m5unified_m5timer_run(void void);
extern int_fast8_t m5unified_m5timer_setTimer(uint32_t interval_msec, timer_callback function, uint32_t times);
extern return m5unified_m5timer_setTimer(interval_msec interval_msec, function function, 0 0);
extern void m5unified_timer_info_t_set(uint32_t interval_msec, timer_callback function, uint32_t times);
extern int m5unified_timer_info_t_run(uint32_t interval_msec);
extern void m5unified_timer_info_t_clear(void void);

/* Method wrappers */
static void mrbc_m5unified_M5Timer(mrbc_vm *vm, mrbc_value *v, int argc) {
  /* void void - unsupported type conversion */
  constructor result = m5unified_m5timer_M5Timer(void);
  /* constructor marshalling not implemented */
}

static void mrbc_m5unified_run(mrbc_vm *vm, mrbc_value *v, int argc) {
  /* void void - unsupported type conversion */
  m5unified_m5timer_run(void);
  SET_RETURN(mrbc_nil_value());
}

static void mrbc_m5unified_setTimer(mrbc_vm *vm, mrbc_value *v, int argc) {
  int interval_msec = v[1].value.i;
  void *function = mrbc_obj_get_ptr(&v[2]);
  int times = v[3].value.i;
  int_fast8_t result = m5unified_m5timer_setTimer(interval_msec, function, times);
  /* int_fast8_t marshalling not implemented */
}

static void mrbc_m5unified_setTimer(mrbc_vm *vm, mrbc_value *v, int argc) {
  void *interval_msec = mrbc_obj_get_ptr(&v[1]);
  void *function = mrbc_obj_get_ptr(&v[2]);
  void *0 = mrbc_obj_get_ptr(&v[3]);
  return result = m5unified_m5timer_setTimer(interval_msec, function, 0);
  /* return marshalling not implemented */
}

static void mrbc_m5unified_set(mrbc_vm *vm, mrbc_value *v, int argc) {
  int interval_msec = v[1].value.i;
  void *function = mrbc_obj_get_ptr(&v[2]);
  int times = v[3].value.i;
  m5unified_timer_info_t_set(interval_msec, function, times);
  SET_RETURN(mrbc_nil_value());
}

static void mrbc_m5unified_run(mrbc_vm *vm, mrbc_value *v, int argc) {
  int interval_msec = v[1].value.i;
  int result = m5unified_timer_info_t_run(interval_msec);
  SET_RETURN(mrbc_bool_value(result));
}

static void mrbc_m5unified_clear(mrbc_vm *vm, mrbc_value *v, int argc) {
  /* void void - unsupported type conversion */
  m5unified_timer_info_t_clear(void);
  SET_RETURN(mrbc_nil_value());
}


void mrbc_mrbgem_picoruby_m5unified_gem_init(mrbc_vm *vm) {
  c_M5Timer = mrbc_define_class(vm, "M5Timer", mrbc_class_object);
  mrbc_define_method(vm, c_M5Timer, "M5Timer", mrbc_m5unified_M5Timer);
  mrbc_define_method(vm, c_M5Timer, "run", mrbc_m5unified_run);
  mrbc_define_method(vm, c_M5Timer, "setTimer", mrbc_m5unified_setTimer);
  mrbc_define_method(vm, c_M5Timer, "setTimer", mrbc_m5unified_setTimer);
  c_timer_info_t = mrbc_define_class(vm, "timer_info_t", mrbc_class_object);
  mrbc_define_method(vm, c_timer_info_t, "set", mrbc_m5unified_set);
  mrbc_define_method(vm, c_timer_info_t, "run", mrbc_m5unified_run);
  mrbc_define_method(vm, c_timer_info_t, "clear", mrbc_m5unified_clear);
}
