# frozen_string_literal: true

require "fileutils"

module M5LibGen
  # Generates complete mrbgem directory structure and files
  class MrbgemGenerator
    attr_reader :output_path

    def initialize(output_path)
      @output_path = output_path
    end

    def generate(cpp_data)
      create_structure
      render_mrbgem_rake
      render_c_bindings(cpp_data)
      render_ruby_lib(cpp_data)
      render_readme(cpp_data)
      render_cpp_wrapper(cpp_data)
      render_cmake
      true
    end

    private

    def create_structure
      FileUtils.mkdir_p(@output_path)
      FileUtils.mkdir_p(File.join(@output_path, "mrblib"))
      FileUtils.mkdir_p(File.join(@output_path, "src"))
      FileUtils.mkdir_p(File.join(@output_path, "ports", "esp32"))
    end

    def render_mrbgem_rake
      content = <<~RUBY
        MRuby::Gem::Specification.new('picoruby-m5unified') do |spec|
          spec.license = 'MIT'
          spec.author  = 'M5LibGen'
          spec.summary = 'M5Unified bindings for PicoRuby'
        end
      RUBY
      File.write(File.join(@output_path, "mrbgem.rake"), content)
    end

    def render_c_bindings(cpp_data)
      content = "/* M5Unified C Bindings for PicoRuby */\n"
      content += "#include <mrubyc.h>\n\n"
      content += generate_forward_declarations(cpp_data)
      content += generate_function_wrappers(cpp_data)
      content += generate_gem_init(cpp_data)
      File.write(File.join(@output_path, "src", "m5unified.c"), content)
    end

    def generate_forward_declarations(cpp_data)
      content = "/* Forward declarations */\n"
      cpp_data.each do |klass|
        content += "static mrbc_class *c_#{klass[:name]};\n"
      end
      content += "\n/* Extern function declarations */\n"
      cpp_data.each do |klass|
        klass[:methods].each do |method|
          func_name = "m5unified_#{klass[:name].downcase}_#{method[:name]}"
          content += "extern void #{func_name}(void);\n"
        end
      end
      "#{content}\n"
    end

    def generate_function_wrappers(cpp_data)
      content = "/* Method wrappers */\n"
      cpp_data.each do |klass|
        klass[:methods].each do |method|
          content += generate_method_wrapper(klass[:name], method)
        end
      end
      "#{content}\n"
    end

    def generate_method_wrapper(_class_name, method)
      func_name = "mrbc_m5_#{method[:name]}"
      content = "static void #{func_name}(mrbc_vm *vm, mrbc_value *v, int argc) {\n"
      content += "  /* TODO: Call wrapper function */\n"
      content += "  SET_RETURN(mrbc_nil_value());\n"
      content += "}\n\n"
      content
    end

    def generate_gem_init(cpp_data)
      content = "void mrbc_mrbgem_picoruby_m5unified_gem_init(mrbc_vm *vm) {\n"
      cpp_data.each do |klass|
        content += "  c_#{klass[:name]} = mrbc_define_class(vm, \"#{klass[:name]}\", mrbc_class_object);\n"
        klass[:methods].each do |method|
          method_func = "mrbc_m5_#{method[:name]}"
          content += "  mrbc_define_method(vm, c_#{klass[:name]}, \"#{method[:name]}\", #{method_func});\n"
        end
      end
      "#{content}}\n"
    end

    def render_ruby_lib(cpp_data)
      content = "# M5Unified Ruby bindings\n"
      content += "# Auto-generated by M5LibGen\n\n"
      cpp_data.each { |klass| content += "# Class: #{klass[:name]}\n" }
      File.write(File.join(@output_path, "mrblib", "m5unified.rb"), content)
    end

    def render_readme(cpp_data)
      content = "# picoruby-m5unified\n\n"
      content += "M5Unified bindings for PicoRuby.\n\n"
      content += "## Classes\n\n"
      cpp_data.each { |klass| content += "- #{klass[:name]}\n" }
      content += "\n## License\n\nMIT\n"
      File.write(File.join(@output_path, "README.md"), content)
    end

    def render_cpp_wrapper(cpp_data)
      generator = CppWrapperGenerator.new(cpp_data)
      content = generator.generate
      File.write(File.join(@output_path, "ports", "esp32", "m5unified_wrapper.cpp"), content)
    end

    def render_cmake
      generator = CMakeGenerator.new
      content = generator.generate
      File.write(File.join(@output_path, "CMakeLists.txt"), content)
    end
  end
end
